### ISSUE TITLE
Document initial setup

### ISSUE THREAD

**Issue by mitchhentges** [mpapierski/issues#2]
I'm not super familiar with python which is making it tricky to get `issues` working :laughing: 

Here's what I did:

1. `chmod +x setup.py`
2. `./setup.py setup`
3. `python3 ./build/lib/issues/cli.py`

I get the following error:
```
Traceback (most recent call last):
  File "./build/lib/issues/cli.py", line 2, in <module>
    from commands import collection
ModuleNotFoundError: No module named 'commands'
```

Here's the file structure of `build` (I can't find `commands` in there):
```
build
└── lib
    └── issues
        ├── cli.py
        ├── database.py
        ├── database_tests.py
        └── __init__.py

2 directories, 4 files
```

I'm running Python `3.6.5` :smile:

**Comment by mpapierski** [comment]
Thanks for opening this issue. It might be a cause that py3k is not supported. I'll look into it.

**Comment by mitchhentges** [comment]
I'll try with Python 2 as well (I have version `2.7.15` installed). So, this time, I ran:

1. `python2 setup.py build`
2. `python2 build/lib/issues/cli.py`

I still got an error, though :cry: 

```
Traceback (most recent call last):
  File "build/lib/issues/cli.py", line 1, in <module>
    import click
ImportError: No module named click
```

File structure again to show it didn't change:
```
build
└── lib
    └── issues
        ├── cli.py
        ├── database.py
        ├── database_tests.py
        └── __init__.py

2 directories, 4 files
```
